sudo: required
dist: trusty
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - VERBOSE_OUTPUT=true
    - export PYTHONPATH=$PWD/ros_opcua_impl_python_opcua/python-opcua:$PYTHONPATH
  matrix:
    - ROS_DISTRO="kinetic" ADDITIONAL_DEBS="libxml2-dev"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script
