controller_list:
  - name: fake_robot_arm_controller
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
  - name: fake_hand_controller
    joints:
      - Joint6